### ISSUE TITLE
Set allowed dependency versions

### ISSUE THREAD

**Issue by alagos** [amatsuda/routes_lazy_routes#16]
I just installed the gem with the hope that worked with a ruby 2.4/rails 4.2 stack (I'm aware that both aren't supported anymore) and when I started the app I got:
```
/Users/alter/.rbenv/versions/2.4.10/lib/ruby/gems/2.4.0/gems/railties-4.2.11.3/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>': undefined method `execute_if_updated' for #<RoutesLazyRoutes::RoutesReloaderWrapper:0x0000000105243dc0> (NoMethodError)
	from /Users/alter/.rbenv/versions/2.4.10/lib/ruby/gems/2.4.0/gems/railties-4.2.11.3/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/alter/.rbenv/versions/2.4.10/lib/ruby/gems/2.4.0/gems/railties-4.2.11.3/lib/rails/initializable.rb:30:in `run'
	from /Users/alter/.rbenv/versions/2.4.10/lib/ruby/gems/2.4.0/gems/railties-4.2.11.3/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /Users/alter/.rbenv/versions/2.4.10/lib/ruby/2.4.0/tsort.rb:228:in `block in tsort_each'
	from /Users/alter/.rbenv/versions/2.4.10/lib/ruby/2.4.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /Users/alter/.rbenv/versions/2.4.10/lib/ruby/2.4.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /Users/alter/.rbenv/versions/2.4.10/lib/ruby/2.4.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /Users/alter/.rbenv/versions/2.4.10/lib/ruby/2.4.0/tsort.rb:347:in `each'
	from /Users/alter/.rbenv/versions/2.4.10/lib/ruby/2.4.0/tsort.rb:347:in `call'
	from /Users/alter/.rbenv/versions/2.4.10/lib/ruby/2.4.0/tsort.rb:347:in `each_strongly_connected_component'
	from /Users/alter/.rbenv/versions/2.4.10/lib/ruby/2.4.0/tsort.rb:226:in `tsort_each'
	from /Users/alter/.rbenv/versions/2.4.10/lib/ruby/2.4.0/tsort.rb:205:in `tsort_each'
	from /Users/alter/.rbenv/versions/2.4.10/lib/ruby/gems/2.4.0/gems/railties-4.2.11.3/lib/rails/initializable.rb:54:in `run_initializers'
	from /Users/alter/.rbenv/versions/2.4.10/lib/ruby/gems/2.4.0/gems/railties-4.2.11.3/lib/rails/application.rb:352:in `initialize!'
	from /Users/alter/.rbenv/versions/2.4.10/lib/ruby/gems/2.4.0/gems/railties-4.2.11.3/lib/rails/railtie.rb:194:in `public_send'
	from /Users/alter/.rbenv/versions/2.4.10/lib/ruby/gems/2.4.0/gems/railties-4.2.11.3/lib/rails/railtie.rb:194:in `method_missing'
```
So might be good to have [a version restriction](https://github.com/amatsuda/routes_lazy_routes/blob/master/routes_lazy_routes.gemspec#L28-L29) defined in the gemspec.
